# Generated by Django 4.2.7 on 2023-12-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0002_patient_blood_group_patient_date_of_birth'),
        ('doctor', '0014_rename_certificates_pdf_certificatespdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(choices=[('09:00-09:30 AM', '09:00-09:30 AM'), ('10:00-10:30 AM', '10:00-10:30 AM'), ('11:00-11:30 AM', '11:00-11:30 AM'), ('12:00-12:30 PM', '12:00-12:30 PM'), ('1:00-1:30 PM', '1:00-1:30 PM'), ('2:00-2:30 PM', '2:00-2:30 PM'), ('3:00-3:30 PM', '3:00-3:30 PM'), ('4:00-4:30 PM', '4:00-4:30 PM'), ('5:00-5:30 PM', '5:00-5:30 PM'), ('6:00-6:30 PM', '6:00-6:30 PM'), ('7:00-7:30 PM', '7:00-7:30 PM'), ('8:00-8:30 PM', '8:00-8:30 PM')])),
                ('is_booked', models.BooleanField(default=False)),
                ('doctorr', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Missed', 'Missed')], max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
