# Generated by Django 4.2.7 on 2023-12-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0002_alter_availableslot_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslot',
            name='time',
            field=models.CharField(choices=[('09:00-09:30 AM', '09:00-09:30 AM'), ('09:30-10:00 AM', '09:30-10:00 AM'), ('10:00-10:30 AM', '10:00-10:30 AM'), ('10:30-11:00 AM', '10:30-11:00 AM'), ('11:00-11:30 AM', '11:00-11:30 AM'), ('11:30-12:00 AM', '11:30-12:00 AM'), ('12:00-12:30 PM', '12:00-12:30 PM'), ('1:00-1:30 PM', '1:00-1:30 PM'), ('1:30-2:00 PM', '1:30-2:00 PM'), ('2:00-2:30 PM', '2:00-2:30 PM'), ('2:30-3:00 PM', '2:30-3:00 PM'), ('3:00-3:30 PM', '3:00-3:30 PM'), ('3:30-4:00 PM', '3:30-4:00 PM'), ('4:00-4:30 PM', '4:00-4:30 PM'), ('4:30-5:00 PM', '4:30-5:00 PM'), ('5:00-5:30 PM', '5:00-5:30 PM'), ('5:30-6:00 PM', '5:30-6:00 PM'), ('6:00-6:30 PM', '6:00-6:30 PM'), ('7:00-7:30 PM', '7:00-7:30 PM'), ('8:00-8:30 PM', '8:00-8:30 PM')]),
        ),
    ]
