# Generated by Django 4.2.7 on 2023-12-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0003_alter_availableslot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Rescheduled', 'Rescheduled'), ('Missed', 'Missed')], default='Confirmed', max_length=20),
        ),
    ]
