# Generated by Django 4.2.7 on 2023-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0005_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='mode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
