# Generated by Django 4.2.7 on 2023-12-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0006_appointment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Refunded', 'Refunded'), ('Missed', 'Missed')], default='Confirmed', max_length=20),
        ),
    ]
