# Generated by Django 4.2.7 on 2023-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_language_doctor_languages_spoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experiance',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages_spoken',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Malayalam', 'Malayalam'), ('Tamil', 'Tamil')], max_length=255, null=True),
        ),
    ]
