# Generated by Django 4.2.7 on 2023-11-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_experience_doctor_experiance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
