# Generated by Django 4.2.7 on 2023-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
