# Generated by Django 4.2.7 on 2023-12-04 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_rename_user_professionaldetails_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetails',
            name='certificates',
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
