# Generated by Django 4.2.7 on 2023-12-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_professionaldetails_certificates_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificates_pdf',
        ),
    ]
