# Generated by Django 4.2.7 on 2023-12-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_rename_certificates_certificates_pdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates_pdf',
            new_name='CertificatesPdf',
        ),
    ]
