# Generated by Django 4.2.7 on 2023-12-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_professionaldetails_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionaldetails',
            name='certificates',
        ),
    ]
