# Generated by Django 4.2.7 on 2023-12-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medcoapp', '0002_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
